strictness: medium
max-line-length: 120
uses:
  - celery
  - flask
requirements:
  - ogreserver/config/requirements.txt
ignore-paths:
  - dedrm/dedrm
  - ogreclient/scripts
  - ogreserver/docs
  - ogreserver/static
  - ogreserver/config
